import express from "express";
import {json} from "express";
import mongoSanitize from "express-mongo-sanitize";
import compression from "compression";
import cors from "cors";
import helmet from "helmet";
import routes from "../routes";
import {handleErrors} from "../middlewares";

const app = express();
app.set("case sensitive routing", false);
app.set("strict routing", false);
app.use(helmet());
app.use(compression());
app.use(json());
app.use(mongoSanitize());
app.use(cors());
app.use(routes);
app.use(handleErrors);
export default app;
